/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.frames;

import br.com.classes.ExerciciosEstagio;
import br.com.classes.ExerciciosEstagioFrame;
import br.com.classes.ArrayJson;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONArray;

/**
 *
 * @author tinho
 */
public class ResultadosDosExercicios extends javax.swing.JFrame {

    ArrayJson x = new ArrayJson();
    ExerciciosEstagio y = new ExerciciosEstagio();
    ExerciciosEstagioFrame z = new ExerciciosEstagioFrame();
    JSONArray jsonArray = null;

    /**
     * Creates new form ResultadosDosExercicios
     */
    public ResultadosDosExercicios() throws URISyntaxException {
        initComponents();
        setLocationRelativeTo(null);
        jsonArray = x.arrayJsonHttps(urljTextField.getText());
        respostaWebTodosjTextPane.setText(y.getWebSitesClientes(jsonArray,
                 "website"));
        respostaEmailUsernamejLabel.setText(y.getEmailByName(jsonArray,
                 "username", "Samantha"));
        respostaQuantidadeSuljLabel.setText(y.getCountSouthUsers(jsonArray,
                 "address", "geo"));

        //    respostaTodosWebSitesjLabel.setText(String.valueOf(y.getUserList(x.arrayJsonHttps(url), "website")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        listajButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        informacoesBasicasUsuariojComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaConsultadajTextPane = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        emailjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        userNameUsuariojTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailConsultadojLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        quantidadejButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        quantidadeSuljLabel = new javax.swing.JLabel();
        hemisferioComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        urljTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        respostaQuantidadeSuljLabel = new javax.swing.JLabel();
        respostaEmailUsernamejLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        respostaWebTodosjTextPane = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        verListaCompletajButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        listajButton.setText("Carregar Lista");
        listajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listajButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Escolha algum desses itens para mostrar a lista completa");

        informacoesBasicasUsuariojComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "name", "username", "email", "phone", "website" }));

        listaConsultadajTextPane.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(listaConsultadajTextPane);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(informacoesBasicasUsuariojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(listajButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(informacoesBasicasUsuariojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listajButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailjButton.setText("Carregar Email");
        emailjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailjButtonActionPerformed(evt);
            }
        });
        jPanel2.add(emailjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 39, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Escreva um nome de username para ver o email !");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 485, -1));
        jPanel2.add(userNameUsuariojTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 232, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Email:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel2.add(emailConsultadojLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 370, 37));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quantidadejButton.setText("Carregar quantidade");
        quantidadejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadejButtonActionPerformed(evt);
            }
        });
        jPanel3.add(quantidadejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 41, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Escolha a opção de Hemisfério para saber a quantidade ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        quantidadeSuljLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(quantidadeSuljLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 140, 51));

        hemisferioComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hemisferioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Norte", "Sul", "Leste", "Oeste" }));
        jPanel3.add(hemisferioComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 39, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("de usuarios localizados");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Quantidade :");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, -1, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        urljTextField.setText("https://jsonplaceholder.typicode.com/users");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Coloque o link da URL HTTPS JSON neste campo, sem espaço, começando com https://");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(urljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(urljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("2) O email da usuária que possui o campo username");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 305, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("1) Os websites de todos os usuários");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("3) EXTRA: Mostrar o total de usuários do hemisfério sul");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 431, -1, -1));

        respostaQuantidadeSuljLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel5.add(respostaQuantidadeSuljLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 471, 264, 33));

        respostaEmailUsernamejLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel5.add(respostaEmailUsernamejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 361, 264, 33));

        respostaWebTodosjTextPane.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(respostaWebTodosjTextPane);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 92, 411, 202));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("RESPOSTAS DO ESTÁGIO");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 11, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("igual a \"Samantha\"");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 333, -1, -1));

        jLabel11.setText("Resposta :");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel12.setText("Resposta :");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel13.setText("Resposta :");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, -1, -1));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        verListaCompletajButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        verListaCompletajButton.setText("Ver Lista Completa");
        verListaCompletajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verListaCompletajButtonActionPerformed(evt);
            }
        });
        jPanel6.add(verListaCompletajButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel16.setText("LISTA COMPLETA ");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void listajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listajButtonActionPerformed

        
        
        String url = urljTextField.getText().trim();
        try {

            listaConsultadajTextPane.setText(z.getUserList(x.arrayJsonHttps(url),
                    informacoesBasicasUsuariojComboBox.getSelectedItem().toString()));

        } catch (URISyntaxException ex) {
            Logger.getLogger(ResultadosDosExercicios.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_listajButtonActionPerformed

    private void emailjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailjButtonActionPerformed

        String url = urljTextField.getText().trim();

        try {
            emailConsultadojLabel.setText(z.getEmailByName(x.arrayJsonHttps(url),
                    userNameUsuariojTextField.getText()));
        } catch (URISyntaxException ex) {
            Logger.getLogger(ResultadosDosExercicios.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_emailjButtonActionPerformed

    private void quantidadejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadejButtonActionPerformed

        String url = urljTextField.getText().trim();

        try {
            quantidadeSuljLabel.setText(z.getCountSulNorteLesteOeste(x.arrayJsonHttps(url),
                     hemisferioComboBox.getSelectedItem().toString()));
            /* quantidadeSuljLabel.setText(z.getCountSouthUsers(x.arrayJsonHttps(url))
                    ,hemisferioComboBox.getSelectedItem().toString());*/
        } catch (URISyntaxException ex) {
            Logger.getLogger(ResultadosDosExercicios.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_quantidadejButtonActionPerformed

    private void verListaCompletajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verListaCompletajButtonActionPerformed

        try {

            new CadastroCompleto().setVisible(true);

        } catch (URISyntaxException ex) {
            Logger.getLogger(ResultadosDosExercicios.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_verListaCompletajButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultadosDosExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultadosDosExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultadosDosExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultadosDosExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ResultadosDosExercicios().setVisible(true);
                } catch (URISyntaxException ex) {
                    Logger.getLogger(ResultadosDosExercicios.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailConsultadojLabel;
    private javax.swing.JButton emailjButton;
    private javax.swing.JComboBox<String> hemisferioComboBox;
    private javax.swing.JComboBox<String> informacoesBasicasUsuariojComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane listaConsultadajTextPane;
    private javax.swing.JButton listajButton;
    private javax.swing.JLabel quantidadeSuljLabel;
    private javax.swing.JButton quantidadejButton;
    private javax.swing.JLabel respostaEmailUsernamejLabel;
    private javax.swing.JLabel respostaQuantidadeSuljLabel;
    private javax.swing.JTextPane respostaWebTodosjTextPane;
    private javax.swing.JTextField urljTextField;
    private javax.swing.JTextField userNameUsuariojTextField;
    private javax.swing.JButton verListaCompletajButton;
    // End of variables declaration//GEN-END:variables
}
